import type { Metadata } from "next";
import "./globals.css";
import AppProviders from "./providers/app-providers";
import { Roboto } from "next/font/google";

const roboto = Roboto({
	weight: ["100", "300", "400", "500", "700"],
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Mar Abu Task Management",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${roboto.className} antialiased`}>
				<AppProviders>{children}</AppProviders>
			</body>
		</html>
	);
}
