import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import AppProviders from "./providers/app-providers";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 400 600 800 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${geistSans.variable} antialiased`}>
				<AppProviders>{children}</AppProviders>
			</body>
		</html>
	);
}
